# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.

# { config, lib, pkgs, modulesPath, ... }:
{ lib, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "usbhid" "usb_storage" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/ccf07b6e-7d72-4bb8-84f5-bd7b8b8d3784";
      fsType = "ext4";
    };
    "/boot" = {
      device = "/dev/disk/by-uuid/8614-8682";
      fsType = "vfat";
    };
  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/58e18194-9ac9-40af-a10f-50fbc6ab4d39"; }];

  powerManagement.cpuFreqGovernor = lib.mkDefault "ondemand";
}
