name: CI
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v5
        with:
          nixpkgs-keys: dotfiles
      - uses: DeterminateSystems/nix-installer-action@v4
      - name: Format
        run: |
          make fmt
          git diff --exit-code
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        host: [hulk, nuc-1, nuc-2, nuc-3]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@v4
      - name: Build
        run: |
          make build \
            ACTIVATION_HOST=${{ matrix.host }}
