name: CI
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v9
      - name: Setup the magic Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v3
      - name: Format
        run: |
          nix develop --command just fmt
          git diff --exit-code
  flake-check:
    name: Flake Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v5
        with:
          nixpkgs-keys: dotfiles
          check-owner: false
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        host: [hulk, nuc-1, nuc-2, nuc-3]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Free space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v9
      # - name: Setup the magic Nix cache
      #   uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: Build
        run: |
          # Force the creation of the profile dir
          nix profile list
          # Build
          nix develop --command just build ${{ matrix.host }}
